/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AuthServer": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "GITHUB_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WWW": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}